//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_IDEA_X.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDEA_XEntities : DbContext
    {
        public IDEA_XEntities()
            : base("name=IDEA_XEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADMIN> ADMINS { get; set; }
        public DbSet<ALL_USERS> ALL_USERS { get; set; }
        public DbSet<CHAT_BOXS> CHAT_BOXS { get; set; }
        public DbSet<CONTACT> CONTACTS { get; set; }
        public DbSet<GENERAL_POSTS> GENERAL_POSTS { get; set; }
        public DbSet<LOGIN> LOGINS { get; set; }
        public DbSet<MESSAGE_REQUESTS> MESSAGE_REQUESTS { get; set; }
        public DbSet<NOTE> NOTES { get; set; }
        public DbSet<POST_ACTIONS> POST_ACTIONS { get; set; }
        public DbSet<POST_REPORT> POST_REPORT { get; set; }
        public DbSet<USER_ACCESS_CONTROLLER> USER_ACCESS_CONTROLLER { get; set; }
        public DbSet<USER_DETAILS> USER_DETAILS { get; set; }
        public DbSet<USER_MESSAGES> USER_MESSAGES { get; set; }
    }
}
