//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_IDEA_X.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public int LOGIN_ID { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string LOGIN_TIME { get; set; }
        public string LOGIN_IP { get; set; }
        public string TOKEN_KEY { get; set; }
        public string EXPIRE_TIME { get; set; }
        public string USER_LEVEL { get; set; }
    }
}
